-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    - id: envalidator
      name: Envalidator
      description: A tool to validate .env files against a .env.example template.
      entry: python main.py
      language: python
      files: ^.env(\.example)?$
      pass_filenames: false